{{- if .Values.certificates.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "planning-poker.fullname" . }}-tls
  labels:
    {{- include "planning-poker.labels" . | nindent 4 }}
spec:
  secretName: {{ include "planning-poker.fullname" . }}-tls
  duration: {{ .Values.certificates.duration }}
  renewBefore: {{ .Values.certificates.renewBefore }}
  subject:
    organizations:
      - Planning Poker
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    {{- range .Values.ingress.hosts }}
    - {{ .host | quote }}
    {{- end }}
  issuerRef:
    name: {{ .Values.certificates.issuerRef.name }}
    kind: {{ .Values.certificates.issuerRef.kind }}
    group: cert-manager.io
{{- end }}