apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  template:
    spec:
      containers:
      - name: redis
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      resources:
        requests:
          storage: 5Gi