## Global settings
nameOverride: ""
fullnameOverride: ""

## Image settings
image:
  repository: sam123ben/planning-poker
  tag: latest
  pullPolicy: IfNotPresent

## Deployment settings
replicaCount: 2
podAnnotations: {}
podSecurityContext: {}
securityContext: {}

## Resource settings
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

## Redis settings
redis:
  enabled: true
  architecture: replication
  auth:
    enabled: true
    existingSecret: redis-credentials
  sentinel:
    enabled: true
    replicas: 3
  persistence:
    enabled: true
    size: 10Gi
  backup:
    enabled: true
    schedule: "0 0 * * *"
    storage:
      className: standard
      size: 10Gi
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

## Certificate settings
certificates:
  enabled: true
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  clusterIssuer:
    create: true
    name: letsencrypt-prod
    email: admin@example.com
    server: https://acme-v02.api.letsencrypt.org/directory

## Ingress settings
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-XSS-Protection: 1; mode=block";
  hosts:
    - host: planning-poker.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: planning-poker-tls
      hosts:
        - planning-poker.example.com

## Service settings
service:
  type: ClusterIP
  port: 80

## Prometheus monitoring settings
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus
    interval: 15s
    scrapeTimeout: 10s
    metricRelabelings:
      - sourceLabels: [__name__]
        regex: 'http_.*'
        action: keep
      - sourceLabels: [__name__]
        regex: 'redis_.*'
        action: keep

## Network Policies
networkPolicies:
  enabled: true
  ingressRules:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
  egressRules:
    - to:
        - namespaceSelector:
            matchLabels:
              name: redis
        ports:
          - protocol: TCP
            port: 6379

## Pod Disruption Budget
pdb:
  enabled: true
  minAvailable: 1

## Autoscaling
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  customMetrics:
    - type: Pods
      pods:
        metric:
          name: http_requests_per_second
        target:
          type: AverageValue
          averageValue: 1000