apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: planning-poker-tls
spec:
  secretName: planning-poker-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  subject:
    organizations:
      - Planning Poker
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - planning-poker.example.com
    - "*.planning-poker.example.com"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io