apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: planning-poker

commonLabels:
  app.kubernetes.io/name: planning-poker
  app.kubernetes.io/part-of: planning-poker

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml
- redis-statefulset.yaml
- env-secret.yaml
- certificate.yaml
- servicemonitor.yaml

configMapGenerator:
- name: planning-poker-config
  literals:
  - NODE_ENV=production