apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: planning-poker
spec:
  selector:
    matchLabels:
      app: planning-poker
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - planning-poker