apiVersion: v1
kind: Secret
metadata:
  name: planning-poker-webhooks
type: Opaque
stringData:
  slack-url: "https://hooks.slack.com/services/your-webhook-url"
  discord-url: "https://discord.com/api/webhooks/your-webhook-url"
  teams-url: "https://your-org.webhook.office.com/webhookb2/your-webhook-url"