name: Build & Push Poker Base Image - Disabled

# on:
#   push:
#     branches: [main]
#     paths:
#       - "Dockerfile-base"
#       - ".github/workflows/build-poker-base.yml"
#       - "package.json"
#       - "package-lock.json"
#   schedule:
#     - cron: "0 12 * * 5" # Runs every Friday at 10 PM AEST (12:00 PM UTC)
#   workflow_dispatch:

env:
  GHCR_REGISTRY: ghcr.io
  IMAGE_NAME: sam123ben/poker-base
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login to GHCR
        run: |
          echo "${{ secrets.CR_GH_PUBLIC_PAT }}" | docker login ghcr.io -u sam123ben --password-stdin

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest

      - name: Build and Push Poker Base Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-base
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max