apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: planning-poker-stage

bases:
- ../../base

commonLabels:
  environment: staging

resources:
- redis-stage.yaml

patches:
- path: patches/deployment.yaml
- path: patches/ingress.yaml
- path: patches/certificate.yaml
- path: patches/cluster-issuer.yaml

configMapGenerator:
- name: planning-poker-config
  behavior: merge
  literals:
  - ENVIRONMENT=staging

secretGenerator:
- name: planning-poker-env
  behavior: merge
  files:
  - .env=env/staging.env